---
- hosts: lemp_www
  become: true

  vars:
    php_version: 8.0
    application_name: laravel
    application_version: 9

  vars_files:
    - "vars/{{ application_name }}-{{ application_version }}.yml"

  roles:
    - name: nginx
    - name: php
      version: "{{ php_version }}"
      # packages: "{{ packages }}"
