---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Ensure keyrings directory exists
  file:
    path: "{{ keyrings_path }}"
    state: directory
    owner: root
    group: root


- name: Import Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution }}/gpg"
    keyring: "{{ docker_keyring_path }}"
    state: present

- name: Install Docker repo
  apt_repository:
    repo: "
      deb [arch=amd64 signed-by={{ docker_keyring_path }}]
      https://download.docker.com/linux/{{ ansible_distribution }}
      {{ ansible_distribution_release }} stable"
