---
- name: Install Docker repo on Fedora
  group:
    - name: Install dnf config manager
      dnf:
        pkg: dnf-plugins-core
        state: present

    - name: Install Docker Fedora repo
      shell: >
        "dnf config-manager --add-repo
        https://download.docker.com/linux/fedora/docker-ce.repo"
  when: "ansible_distribution == 'fedora'"


- name: "Install Docker {{ ansible_distribution }} repo"
  group:
    - name: Install yum config manager
      yum:
        pkg: yum-utils
        state: present

    - name: "Install Docker {{ ansible_distribution }} repo"
      shell: >
        "yum-config-manager --add-repo https://download.docker.com/linux/
        {{ ansible_distribution }}/docker-ce.repo"
        creates: /etc/yum.repos.d/docker-ce.repo
  when: "ansible_distribution in ['centos', 'rhel']"
