---
- hosts: lemp_www
  become: true

  pre_tasks:
    - name: Include MySQL variables
      include_vars: "{{ item }}"
      with_items:
        - vars/mysql_users.yml
        - vars/mysql_databases.yml

  roles:
    - name: mysql
      version: 8.0
