---
packages:
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-ctype
  - php{{ php_version }}-curl
  - php{{ php_version }}-dom
  - php{{ php_version }}-fileinfo
  - php{{ php_version }}-json
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-openssl
  - php{{ php_version }}-pcre
  - php{{ php_version }}-pdo
  - php{{ php_version }}-tokenizer
  - php{{ php_version }}-xml
  - php{{ php_version }}-fpm
