---
- name: Install Python 3 pip
  action: "{{ ansible_pkg_mgr }} name=python3-pip state=present"

- name: Install Python PyMySQL module
  pip:
    name: PyMySQL
    state: present

- name: Include OS-specific mysql install tasks
  include_tasks: "install-mysql-{{ ansible_distribution|lower }}.yml"

- name: Include MySQL secure installation tasks
  include_tasks: "mysql_secure_installation.yml"

- name: Ensure mysql service is started and enabled
  service:
    name: mysql
    state: started
    enabled: true

- name: Ensure all databases are created
  mysql_db:
    name: "{{ mysql_databases }}"
    state: present
  when: "mysql_databases is defined"

- name: Ensure all users are created
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
  with_items: "{{ mysql_users }}"
  when: "mysql_users is defined"
