---
- name: Install dependencies
  include_tasks: "install-dependencies.yml"

- name: Include OS family specific install tasks
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"

- name: Include MySQL secure installation tasks
  include_tasks: "secure-installation.yml"

- include_tasks: "configure.yml"
- include_tasks: "create-databases.yml"
- include_tasks: "create-users.yml"
