---
- name: Set the root password
  mysql_user:
    login_user: ""
    login_password: ""
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  no_log: true

- name: Delete anonymous MySQL server user
  mysql_user:
    user: ""
    state: absent

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
