---
old_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine

new_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
